# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python_application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Run test and create coverage report with pytest
      run: poetry run coverage run --branch -m pytest -W ignore::DeprecationWarning
    - name: Run tests and create coverage report with robot
      run: poetry run coverage run -m robot src/tests
    - name: Run Pylint
      run: poetry run pylint src/
